name: annotations
channels:
  - nostrumbiodiscovery
  - salilab
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - asn1crypto=1.3.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - biopython=1.76=py36h7b6447c_0
  - blas=1.0=openblas
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py36_0
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.8=py36h1ba5d50_0
  - cycler=0.10.0=py36_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dssp=3.0.0=hf484d3e_3
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=hb3b607b_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h211956c_0
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py36_0
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py36_1
  - jinja2=2.11.1=py_0
  - jpeg=9b=habf39ab_1
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter_client=6.1.2=py_0
  - jupyter_cms=0.7.0=py36_1000
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.6.3=py36_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.6=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.0=py_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=11_openblas
  - libboost=1.67.0=h46d08c1_4
  - libcblas=3.8.0=11_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=11_openblas
  - libopenblas=0.3.6=h5a2b251_2
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=3.8.0=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mistune=0.8.4=py36h7b6447c_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - nglview=2.7.5=pyh5ca1d4c_0
  - nodejs=10.13.0=he6710b0_0
  - nomkl=3.0=0
  - notebook=6.0.3=py36_0
  - numpy=1.18.1=py36h94c655d_0
  - numpy-base=1.18.1=py36h2f8d375_1
  - openblas=0.2.19=0
  - openssl=1.1.1=h7b6447c_0
  - pandas=1.0.3=py36h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.6.2=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=20.0.2=py36_1
  - prody=1.10.10=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pyrsistent=0.16.0=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - python=3.6.10=hcf32534_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py36h8c4c3a4_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py36_0
  - scipy=1.2.1=py36h09a28d5_1
  - seaborn=0.10.0=py_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.3=py36_0
  - sip=4.19.13=py36he6710b0_0
  - six=1.14.0=py36_0
  - sortedcontainers=2.1.0=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py36h7b6447c_1
  - traitlets=4.3.3=py36_0
  - urllib3=1.25.8=py36_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.34.2=py36_0
  - whoosh=2.7.4=py_1
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
prefix: /home/mgill/miniconda3/envs/annotations

